import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Movies App</title>
        <h1>Movies</h1>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>Main</div>
      </main>

      <footer className={styles.footer}>Footer</footer>
    </div>
  );
}
