import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";
import getConfig from "next/config";
import Movies from "../pages/src/components/Movies";

const { serverRuntimeConfig, publicRuntimeConfig } = getConfig();

export default function Home(initialData) {
  // başlangıçta boş bir dizi oluşturuldu ardından useEffect ile initialData yüklendiği anda verilerin yüklenmesi sağlandı
  const [search, setSearch] = useState([]);
  useEffect(() => {
    setSearch(initialData.movies.results);
  }, [initialData]);

  return (
    <div className="container">
      <div className={styles.background}>
      <h1 className={styles.h1}>MOVIES APP</h1>
        <Head>
          <title>Movies App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {/* <main className={styles.main}> */}
        <div>
          <Movies />
        </div>
      </div>
      {/* <div>Main</div>
      </main> */}

      {/* <footer className={styles.footer}>Footer</footer> */}
    </div>
  );
}
export async function getServerSideProps(context) {
  //Sayfada kullanılan veriler istek yapıldığı anda alınmak isteniyorsa getServerSideProps fonksiyonu içinde bu veriler alınıp sayfa render işlemi sunucuda yapılabilir. Buna server side rendering denir.
  let movies = await fetch(`
  https://api.themoviedb.org/3/trending/movie/day?api_key=${serverRuntimeConfig.apiKey}`);
  movies = await movies.json();
  return {
    props: { movies: movies },
  };
}
